# Generated by Django 3.1.4 on 2020-12-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_email', models.CharField(max_length=255)),
                ('seller_contact', models.CharField(max_length=255)),
            ],
        ),
    ]
