# Generated by Django 3.1.4 on 2020-12-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20201219_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='seller',
        ),
    ]
