# Generated by Django 3.1.4 on 2020-12-19 18:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20201219_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
