# Generated by Django 3.1.4 on 2020-12-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
