# Generated by Django 3.1.4 on 2020-12-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='SKU',
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
