# Generated by Django 3.1.4 on 2020-12-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_listing_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
